//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sessia3.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materials()
        {
            this.pokupkas = new HashSet<pokupkas>();
        }
    
        public int id_mat { get; set; }
        public string title { get; set; }
        public Nullable<int> count_in_pack { get; set; }
        public Nullable<int> id_unit { get; set; }
        public Nullable<int> count_in_stock { get; set; }
        public Nullable<int> min_count { get; set; }
        public string description { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string image { get; set; }
        public Nullable<int> id_mat_type { get; set; }
    
        public virtual mat_types mat_types { get; set; }
        public virtual units units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pokupkas> pokupkas { get; set; }
    }
}
