//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sessia3.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class pokupkas
    {
        public int id_pokupka { get; set; }
        public Nullable<int> id_prod { get; set; }
        public Nullable<int> id_mat { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual materials materials { get; set; }
        public virtual products products { get; set; }
    }
}
