//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sessia3.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles
    {
        public int id_role { get; set; }
        public string role_name { get; set; }
    }
}
